name: Backend CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'services/**'
      - '.github/workflows/**' # Updated path to catch all workflow changes
  pull_request:
    branches: [ "main" ]
    paths:
      - 'services/**'

jobs:
  build-and-test:
    name: Build and Test Backend Service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # --- ADD THIS DEBUGGING STEP ---
      - name: List files in repository
        run: ls -R

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r services/product-service/requirements.txt

      - name: Run Tests with Pytest
        run: pytest tests/test_product_service.py
