name: Backend CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'services/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'services/**'

jobs:
  build-and-test:
    name: Build, Test, and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r services/product-service/requirements.txt

      - name: Run Tests with Pytest
        run: pytest tests/test_product_service.py

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./services/product-service
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/product-service:latest
